In [1]:
import pandas as pd

In [2]:
df_1 = pd.read_csv('데이터_원본/아이스크림_ICT_2.csv', index_col=0)

In [3]:
df_2 = pd.read_csv('데이터_원본/아이스크림_교과자료.csv')

In [4]:
df_3 = pd.read_csv('데이터_원본/아이스크림_생활지도.csv')

In [5]:
df_4 = pd.read_csv('데이터_원본/아이스크림_어학.csv')

In [6]:
df_5 = pd.read_csv('데이터_원본/아이스크림_자기계발_후기.csv')

In [7]:
df_6 = pd.read_csv('데이터_원본/아이스크림_학급경영_2.csv', index_col=0)

In [8]:
df_7 = pd.read_csv('데이터_원본/아이스크림_학습지도.csv', index_col=0)

In [9]:
df_2.columns = ['연수명', '내용', '별점', '등록일']
df_3.columns = ['연수명', '내용', '별점', '등록일']
df_4.columns = ['연수명', '내용', '별점', '등록일']
df_5.columns = ['연수명', '내용', '별점', '등록일']

In [10]:
df_1.head(3)

,연수명,내용,별점,등록일
0,교사를 위한 구글 활용법(입문자편),"구글의 다양한 활용방법을 쉽고 열정적으로 알려주신 강사님들 모습에 동기부여 받아, ...",rate5,2023.07.31
1,"Z세대의 소통법, 유튜브 활용 교육",유튜브의 전반적인 이해를 할 수 있어 수업 활용에 도움이 되었다.,rate5,2023.07.30
2,교사를 위한 구글 활용법(입문자편),구글의 다양한 기본 활용 방법을 익혀 수업에 활용하는데 도움이 될 거 같다.,rate5,2023.07.30

In [11]:
df_2.head(3)

,연수명,내용,별점,등록일
0,한 학기 한 권 읽기와 교육 연극의 만남,'한 학기 한 권 읽기와 교육연극의 만남' 연수를 통해 학급에서 교사의 수업 전개 ...,rate5,2023.07.28
1,큰별쌤 최태성의 별★별한국사,역사의 흐름을 돌아보며 대한민국의 오늘을 생가하게하는 좋은 연수였습니다.,rate5,2023.07.28
2,연수로 완성하는 아이스크림 과학 교과서(4학년),안녕하세요? 오랫만에 아이스크림 연수를 받으니 반갑네요~\n2학기 지도를 준비하며 ...,rate5,2023.07.28

In [12]:
df_3.head(3)

,연수명,내용,별점,등록일
0,신영일과 함께하는 안전교육 365,"안전 연수 올 해 꼭 받아야 하는데, 부담 없이 편안한 마음으로 마쳤어요.~",rate4,2023.07.27
1,최민준&김택수의 위대한 녀석들,기대를 너무 한 건지 너무 이상적인 내용만 전달하는 것 같습니다.\n교사들의 이해를...,rate3,2023.07.27
2,아이들의 내면이 단단해지는 격려수업,요즘 부쩍 생활지도의 어려움을 많이 느낀다.\n이번 연수를 통해 다시 한번 그 아이...,rate5,2023.07.27

In [13]:
df_4.head(3)

,연수명,내용,별점,등록일
0,"상식+, 영어로 스마트하게 말하기",상식적으로 대충 알고 있는 영어를 확실하게 재정립했습니다.,rate5,2023.07.27
1,영어로 세계 속으로 with 내셔널 지오그래픽,평소 영어를 사용할 수 없는 환경에서 생활하는데 영어 수업을 하려니 입에 붙지 않는...,rate5,2023.07.26
2,5분 만에 끝내는 여행영어,부담없고 쉽고 간편한 영어를 두분 케미로 보여주셔서 감사합니다~~\n영어 왕보초도 ...,rate5,2023.07.25

In [14]:
df_5.head(3)

,연수명,내용,별점,등록일
0,나만의 이미지 가치를 높여주는 퍼스널 컬러 스타일링,"막연했던 웜톤과 쿨톤, 4타입(봄, 여름, 가을, 겨울)에 대해 알게 되었다.",rate5,2023.07.31
1,알면 편한 심리학 with 유미의 세포들,인간 심리에 대해 궁금하신 분들이 이수하면 좋을 듯 합니다,rate5,2023.07.31
2,"감성을 엮는 시간, 라탄 공예",라탄 공예의 기본을 익혀 생활 속에서 필요한 소품 제작 및 학생 수업에 활용해야겠다.,rate5,2023.07.30

In [15]:
df_6.head(3)

,연수명,내용,별점,등록일
0,비접촉 놀이로 행복 가득 기분 좋은 교실,심혈을 기울여 만든 비접촉 놀이 연수였던 것 같습니다. 유익했습니다. 감사합니다.,rate5,2023.07.29
1,흔들리지 않는 교실을 위한 단호한 학급운영,넘 좋아요! 많은 선생님들께 강추합니다. 교실에서 꼭 필요한 내용이고 강의도 알찹니...,rate5,2023.07.28
2,본격! 청개구리 학생심리 사로잡기,30년 가까이 일하면서도 놓치고 있었던 것들을 알려주었습니다. 그리고 무조건 교사 ...,rate5,2023.07.28

In [16]:
df_7.head(3)

,연수명,내용,별점,등록일
0,유초등을 사로잡는 감동의 그림책 놀이수업,너무 유익한 강의였습니다. 감사합니다^^,rate5,2023.07.28
1,전문가가 알려주는 창의 영재교육의 비법,무엇보다도 빨리들을 수 있어 좋습니다,rate5,2023.07.28
2,"챗GPT 융합교육 가이드, 인공지능(AI) 챗봇 수업",제목을 보고 평소에 많이 들어본 것이라 어떻게 접목을 할 수 있을까 고민을 하다 들...,rate5,2023.07.27

In [17]:
df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7])

In [18]:
df

,연수명,내용,별점,등록일
0,교사를 위한 구글 활용법(입문자편),"구글의 다양한 활용방법을 쉽고 열정적으로 알려주신 강사님들 모습에 동기부여 받아, ...",rate5,2023.07.31
1,"Z세대의 소통법, 유튜브 활용 교육",유튜브의 전반적인 이해를 할 수 있어 수업 활용에 도움이 되었다.,rate5,2023.07.30
2,교사를 위한 구글 활용법(입문자편),구글의 다양한 기본 활용 방법을 익혀 수업에 활용하는데 도움이 될 거 같다.,rate5,2023.07.30
3,교사를 위한 구글 활용법(입문자편),요즘 구글로 자료를 수집하고 구글을 통해 아이들과 수업도 하는데 처음에는 익숙하지 ...,rate5,2023.07.28
4,"가장 쉬운 수업도구, 패들렛과 띵커벨",패들렛과 띵커벨 활용하고 있었으나 다양한 교과에 특히 독서 지도에 많이 활용 할 수...,rate5,2023.07.28
...,...,...,...,...
2820,꿈과 자존감이 자라는 교실 속 직업놀이 진로교육,교실현장에서 아이들 특색맞춰 지도할 팁이 되었습니다,rate5,2022.01.01
2821,프로젝트수업으로 시작하는 교실 속 디자인씽킹,추천합니다!,rate5,2022.01.01
2822,"참쌤스쿨 그림교실, 교사가 최고의 콘텐츠다",학교에서 만나는 아이들은 그림을 참 좋아한다. 연수 후기를 보다가 좋은 연수 같아서...,rate5,2022.01.01
2823,Let's AI 인공지능 교육 활용편,현실적으로 우리 생활 속에 많이 활용되고 있은 인공지능에 대해 알 수 있는 기회가 ...,rate5,2022.01.01
2824,놀이와 질문이 함께하는 감동의 그림책 수업,"처음 독서수업을 하려고 준비할때 막막했는데, [놀이와 질문이 함께하는 감동의 그림책...",rate5,2022.01.01

In [19]:
df.iloc[1,2 ].lstrip('rate')

'5'

In [20]:
for i in range(len(df)):
    df.iloc[i, 2] = df.iloc[i, 2].lstrip('rate')

In [21]:
df['별점'].unique()

array(['5', '3', '4', '2', '1'], dtype=object)

In [22]:
df['분류'] = None

In [23]:
for i in range(len(df)):
    if (df.iloc[i, 2] == '5') or (df.iloc[i, 2] == '4'):
        df.iloc[i, 4] = '긍정'
    else:
        df.iloc[i, 4] = '부정'

In [24]:
df['분류'].unique()

array(['긍정', '부정'], dtype=object)

In [25]:
df['별점'] = df['별점'].astype(int)

In [26]:
df

,연수명,내용,별점,등록일,분류
0,교사를 위한 구글 활용법(입문자편),"구글의 다양한 활용방법을 쉽고 열정적으로 알려주신 강사님들 모습에 동기부여 받아, ...",5,2023.07.31,긍정
1,"Z세대의 소통법, 유튜브 활용 교육",유튜브의 전반적인 이해를 할 수 있어 수업 활용에 도움이 되었다.,5,2023.07.30,긍정
2,교사를 위한 구글 활용법(입문자편),구글의 다양한 기본 활용 방법을 익혀 수업에 활용하는데 도움이 될 거 같다.,5,2023.07.30,긍정
3,교사를 위한 구글 활용법(입문자편),요즘 구글로 자료를 수집하고 구글을 통해 아이들과 수업도 하는데 처음에는 익숙하지 ...,5,2023.07.28,긍정
4,"가장 쉬운 수업도구, 패들렛과 띵커벨",패들렛과 띵커벨 활용하고 있었으나 다양한 교과에 특히 독서 지도에 많이 활용 할 수...,5,2023.07.28,긍정
...,...,...,...,...,...
2820,꿈과 자존감이 자라는 교실 속 직업놀이 진로교육,교실현장에서 아이들 특색맞춰 지도할 팁이 되었습니다,5,2022.01.01,긍정
2821,프로젝트수업으로 시작하는 교실 속 디자인씽킹,추천합니다!,5,2022.01.01,긍정
2822,"참쌤스쿨 그림교실, 교사가 최고의 콘텐츠다",학교에서 만나는 아이들은 그림을 참 좋아한다. 연수 후기를 보다가 좋은 연수 같아서...,5,2022.01.01,긍정
2823,Let's AI 인공지능 교육 활용편,현실적으로 우리 생활 속에 많이 활용되고 있은 인공지능에 대해 알 수 있는 기회가 ...,5,2022.01.01,긍정
2824,놀이와 질문이 함께하는 감동의 그림책 수업,"처음 독서수업을 하려고 준비할때 막막했는데, [놀이와 질문이 함께하는 감동의 그림책...",5,2022.01.01,긍정

In [27]:
df['별점'].unique()

array([5, 3, 4, 2, 1])

In [28]:
df['분류'].unique()

array(['긍정', '부정'], dtype=object)

In [33]:
df[:3]

,연수명,내용,별점,등록일,분류
0,교사를 위한 구글 활용법(입문자편),"구글의 다양한 활용방법을 쉽고 열정적으로 알려주신 강사님들 모습에 동기부여 받아, ...",5,2023.07.31,긍정
1,"Z세대의 소통법, 유튜브 활용 교육",유튜브의 전반적인 이해를 할 수 있어 수업 활용에 도움이 되었다.,5,2023.07.30,긍정
2,교사를 위한 구글 활용법(입문자편),구글의 다양한 기본 활용 방법을 익혀 수업에 활용하는데 도움이 될 거 같다.,5,2023.07.30,긍정

In [38]:
df = df.drop([0, 1, 2], axis=0) # 28일 이전 데이터 삭제

In [41]:
df.reset_index(drop=True, inplace=True)

In [42]:
df

,연수명,내용,별점,등록일,분류
0,교사를 위한 구글 활용법(입문자편),요즘 구글로 자료를 수집하고 구글을 통해 아이들과 수업도 하는데 처음에는 익숙하지 ...,5,2023.07.28,긍정
1,"가장 쉬운 수업도구, 패들렛과 띵커벨",패들렛과 띵커벨 활용하고 있었으나 다양한 교과에 특히 독서 지도에 많이 활용 할 수...,5,2023.07.28,긍정
2,교사를 위한 구글 활용법(입문자편),업무 효율을 높여주는 연수~~,5,2023.07.25,긍정
3,"Z세대의 소통법, 유튜브 활용 교육",수업 중 유튜브를 활용할 수 있는 방법을 알게 되었습니다.,5,2023.07.24,긍정
4,쌍방향이 가능한 온라인 수업 방법 및 도구 활용,감염병때문에 온라인 수업 할 일이 많았는데 도움이 됐어요,5,2023.07.21,긍정
...,...,...,...,...,...
12020,꿈과 자존감이 자라는 교실 속 직업놀이 진로교육,교실현장에서 아이들 특색맞춰 지도할 팁이 되었습니다,5,2022.01.01,긍정
12021,프로젝트수업으로 시작하는 교실 속 디자인씽킹,추천합니다!,5,2022.01.01,긍정
12022,"참쌤스쿨 그림교실, 교사가 최고의 콘텐츠다",학교에서 만나는 아이들은 그림을 참 좋아한다. 연수 후기를 보다가 좋은 연수 같아서...,5,2022.01.01,긍정
12023,Let's AI 인공지능 교육 활용편,현실적으로 우리 생활 속에 많이 활용되고 있은 인공지능에 대해 알 수 있는 기회가 ...,5,2022.01.01,긍정
12024,놀이와 질문이 함께하는 감동의 그림책 수업,"처음 독서수업을 하려고 준비할때 막막했는데, [놀이와 질문이 함께하는 감동의 그림책...",5,2022.01.01,긍정

In [43]:
df.to_csv('i_data_2023_2022.csv')

In [44]:
df_list = pd.read_csv('i_data_2023_2022.csv', index_col=0)  
df_list

,연수명,내용,별점,등록일,분류
0,교사를 위한 구글 활용법(입문자편),요즘 구글로 자료를 수집하고 구글을 통해 아이들과 수업도 하는데 처음에는 익숙하지 ...,5,2023.07.28,긍정
1,"가장 쉬운 수업도구, 패들렛과 띵커벨",패들렛과 띵커벨 활용하고 있었으나 다양한 교과에 특히 독서 지도에 많이 활용 할 수...,5,2023.07.28,긍정
2,교사를 위한 구글 활용법(입문자편),업무 효율을 높여주는 연수~~,5,2023.07.25,긍정
3,"Z세대의 소통법, 유튜브 활용 교육",수업 중 유튜브를 활용할 수 있는 방법을 알게 되었습니다.,5,2023.07.24,긍정
4,쌍방향이 가능한 온라인 수업 방법 및 도구 활용,감염병때문에 온라인 수업 할 일이 많았는데 도움이 됐어요,5,2023.07.21,긍정
...,...,...,...,...,...
12020,꿈과 자존감이 자라는 교실 속 직업놀이 진로교육,교실현장에서 아이들 특색맞춰 지도할 팁이 되었습니다,5,2022.01.01,긍정
12021,프로젝트수업으로 시작하는 교실 속 디자인씽킹,추천합니다!,5,2022.01.01,긍정
12022,"참쌤스쿨 그림교실, 교사가 최고의 콘텐츠다",학교에서 만나는 아이들은 그림을 참 좋아한다. 연수 후기를 보다가 좋은 연수 같아서...,5,2022.01.01,긍정
12023,Let's AI 인공지능 교육 활용편,현실적으로 우리 생활 속에 많이 활용되고 있은 인공지능에 대해 알 수 있는 기회가 ...,5,2022.01.01,긍정
12024,놀이와 질문이 함께하는 감동의 그림책 수업,"처음 독서수업을 하려고 준비할때 막막했는데, [놀이와 질문이 함께하는 감동의 그림책...",5,2022.01.01,긍정

In [45]:
df_list[df_list['분류'] == '부정']

,연수명,내용,별점,등록일,분류
6,교사를 위한 구글 활용법(입문자편),초보자들을 위한 연수라고 해서 들었는데 15차시라서 그런지\n뭔가 겉핥기만 한 느낌...,3,2023.07.19,부정
84,"가장 쉬운 수업도구, 패들렛과 띵커벨",좋은연수감사합니다,3,2023.05.02,부정
121,"가장 쉬운 수업도구, 패들렛과 띵커벨",아이스크림 띵커벨을 배울려고했는데.....패들렛 연수인 것 같네요.\n전적인 띵커벨...,3,2023.04.16,부정
128,"엑셀의 신, 학교에서 쓰는 쉬운 엑셀",도움이 됩니다 후후맨!,3,2023.04.12,부정
130,"탤짱쌤의 컴퓨터 활용 꼼수, 이 정도면 나도 스마트",저는 남는 게 별로 없었습니다.\n개인적으로 이도 저도 아닌 듯한 연수였어요.,3,2023.04.11,부정
...,...,...,...,...,...
11795,"완벽한 혁신을 위한 교육과정, 수업, 평가, 기록의 일체화",저는 초등교사입니다.\n교수평기 일체화에서 평가에 대해 알고 싶었는데 평가보다는 수...,2,2022.02.09,부정
11797,두근두근! 1학년을 만나는 교사를 위한 한해살이 완벽 가이드 - 생활지도,"1학년을 해보아서 알고 있는 내용도 나오지만 더 심화된, 필수 내용도 알 수 있어서...",3,2022.02.09,부정
11876,정재승의 미래학교,"좀 더 전문적인 내용이면 좋겠다. 유투브, 블로그 등을 통해 쉽게 구할 수 있는 일...",3,2022.01.24,부정
11888,디지털 네이티브 아이들의 메타버스 세상,지난 2년간 비대면수업이 이루어지면서 메타버스와 가상현실에 대한 관심이 조금 생겨 ...,3,2022.01.22,부정
11930,독서지도사 양성과정1,제가 필요로 했던 연수와 초점이 조금 달라 아쉬웠어요\n\n그래도 이왕 듣는김에 '...,2,2022.01.17,부정